server:
  port: 8989
  servlet:
    context-path: /bank-api

spring:
  security:
    user:
      name: ${BANK_APP_USER:bankapp}
      password: ${BANK_APP_PASSWORD:changeit}
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
