server.port: 8989
server.servlet.context-path: /bank-api

spring.security.user.name: ${BANK_APP_USERNAME:bankapp}
spring.security.user.password: ${BANK_APP_PASSWORD:changeit}

# Enabling H2 Console
spring:
  h2:
    console:
      enabled: true
