DROP TABLE IF EXISTS TRANSACTION CASCADE;
DROP TABLE IF EXISTS CUSTOMER_ACCOUNTXREF CASCADE;
DROP TABLE IF EXISTS ACCOUNT CASCADE;
DROP TABLE IF EXISTS CUSTOMER CASCADE;
DROP TABLE IF EXISTS BANK_INFO CASCADE;
DROP TABLE IF EXISTS CONTACT CASCADE;
DROP TABLE IF EXISTS ADDRESS CASCADE;

CREATE TABLE ADDRESS (
    ADDR_ID UUID NOT NULL DEFAULT RANDOM_UUID(),
    ADDRESS1 VARCHAR(255),
    ADDRESS2 VARCHAR(255),
    CITY VARCHAR(255),
    COUNTRY VARCHAR(255),
    STATE VARCHAR(255),
    ZIP VARCHAR(255),
    PRIMARY KEY (ADDR_ID)
);

CREATE TABLE CONTACT (
    CONTACT_ID UUID NOT NULL DEFAULT RANDOM_UUID(),
    EMAIL_ID VARCHAR(255),
    HOME_PHONE VARCHAR(255),
    WORK_PHONE VARCHAR(255),
    PRIMARY KEY (CONTACT_ID)
);

CREATE TABLE BANK_INFO (
    BANK_ID UUID NOT NULL DEFAULT RANDOM_UUID(),
    BRANCH_CODE INTEGER,
    BRANCH_NAME VARCHAR(255),
    ROUTING_NUMBER INTEGER,
    BRANCH_ADDRESS_ADDR_ID UUID,
    PRIMARY KEY (BANK_ID),
    FOREIGN KEY (BRANCH_ADDRESS_ADDR_ID) REFERENCES ADDRESS(ADDR_ID)
);

CREATE TABLE ACCOUNT (
    ACCT_ID UUID NOT NULL DEFAULT RANDOM_UUID(),
    ACCOUNT_BALANCE DOUBLE,
    ACCOUNT_NUMBER BIGINT,
    ACCOUNT_STATUS VARCHAR(255),
    ACCOUNT_TYPE VARCHAR(255),
    CREATE_DATE_TIME TIME,
    UPDATE_DATE_TIME TIME,
    BANK_INFORMATION_BANK_ID UUID,
    PRIMARY KEY (ACCT_ID),
    FOREIGN KEY (BANK_INFORMATION_BANK_ID) REFERENCES BANK_INFO(BANK_ID)
);

CREATE TABLE CUSTOMER (
    CUST_ID UUID NOT NULL DEFAULT RANDOM_UUID(),
    CREATE_DATE_TIME TIME,
    CUSTOMER_NUMBER BIGINT,
    FIRST_NAME VARCHAR(255),
    LAST_NAME VARCHAR(255),
    MIDDLE_NAME VARCHAR(255),
    STATUS VARCHAR(255),
    UPDATE_DATE_TIME TIME,
    CONTACT_DETAILS_CONTACT_ID UUID,
    CUSTOMER_ADDRESS_ADDR_ID UUID,
    PRIMARY KEY (CUST_ID),
    FOREIGN KEY (CONTACT_DETAILS_CONTACT_ID) REFERENCES CONTACT(CONTACT_ID),
    FOREIGN KEY (CUSTOMER_ADDRESS_ADDR_ID) REFERENCES ADDRESS(ADDR_ID)
);

CREATE TABLE CUSTOMER_ACCOUNTXREF (
    CUST_ACC_XREF_ID UUID NOT NULL DEFAULT RANDOM_UUID(),
    ACCOUNT_NUMBER BIGINT UNIQUE,
    CUSTOMER_NUMBER BIGINT,
    PRIMARY KEY (CUST_ACC_XREF_ID)
);

CREATE TABLE TRANSACTION (
    TX_ID UUID NOT NULL DEFAULT RANDOM_UUID(),
    ACCOUNT_NUMBER BIGINT,
    TX_AMOUNT DOUBLE,
    TX_DATE_TIME TIMESTAMP,
    TX_TYPE VARCHAR(255),
    PRIMARY KEY (TX_ID)
);
