name: Tests
on:
  pull_request:
    paths-ignore: ["**.md"]
  push:
    branches: [ main, master ]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - { lang: java, os: ubuntu-latest, java: "8" }
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - if: matrix.lang == 'java'
        uses: actions/setup-java@v4
        with: 
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: maven
      
      - if: matrix.lang == 'java'
        name: Run tests with coverage
        run: |
          mvn clean verify
      
      - if: matrix.lang == 'java'
        name: Upload coverage reports
        uses: codecov/codecov-action@v4
        with:
          file: ./target/site/jacoco/jacoco.xml
          fail_ci_if_error: false
